### ISSUE TITLE
BS-2019: Svetainė: neparametriniam → parametriniam

### ISSUE THREAD

**Issue by DanasKl** [mokymai/taisymai--r-2019#48]
1. **Kursas:** Biostatistika (BS-2019)
2. **Netikslumo vieta:** svetainė
3. **Nuoroda (URL):** https://mokymai.github.io/analize-2019/ht-ivadas.html
4. **Glaustai aprašykite netikslumą:** parašyta "Jei pažeidžiamos **neparametriniam** kriterijui keliamos sąlygos, geriau rinktis neparametrinį", nors turėtų būti **"parametriniam**"/

5. **Nukopijuokite visą sakinį su netikslumu:** Jei pažeidžiamos neparametriniam kriterijui keliamos sąlygos, geriau rinktis neparametrinį
6. **Netikslumo tekstas:** neparametriniam
7. **Siūlomas taisymo tekstas:** parametriniam
8. **Ekrano nuotrauka („Screenshots“)** 
![image](https://user-images.githubusercontent.com/56915983/71816443-49810100-308b-11ea-8024-603ff5e7406a.png)

**Comment by GegznaV** [comment]
#45
