### ISSUE TITLE
BS-2019 skaidrės P08-1:  kvanrtiliai → kvantiliai

### ISSUE THREAD

**Issue by Auguste11** [mokymai/taisymai--r-2019#7]
1. **Kursas:** Biostatistika (BS-2019)
2. **Netikslumo vieta:** skaidrės 
3. **Skaidrių bloko pavadinimas ir versija:** P08-1 v1.0 
4. **Bylos pavadinimas:** qq-diagrama.pdf
5. **Skaidrės numeris:** 3
6. **Glaustai aprašykite netikslumą:**    Rašybos klaida
7. **Nukopijuokite visą sakinį su netikslumu:** 
 Teorinio modelio kvanrtiliai
8. **Netikslumo tekstas:**   kvanrtiliai
9. **Siūlomas taisymo tekstas:**  kvantiliai
10. **Ekrano nuotrauka („Screenshots“)** su pažymėta netikslumo vieta.
...

**Comment by GegznaV** [comment]
1) Kitą kartą pateikite PrintScreen. Šiam tikslui galite naudoti nemokamą programos https://picpick.app/en/ versiją. 
2) Taip pat tiksliau nurodykite klaidos esmę temos pavadinime, nes pvz., #8 yra besikartojantis pranešimas.
